services:
  #Database service
  db:
    image: postgres:latest
    container_name: my_db_compose
    ports:
      - "55432:5432"
    environment:
      POSTGRES_DB: suriyan
      POSTGRES_USER: suriyan
      POSTGRES_PASSWORD: suriyan
    networks:
      - strapi-net

  #strapi service
  strapi:
    image: prawee/strapi:latest
    container_name: my_app_compose
    ports:
      - "8080:1337"
    volumes: 
      - "./strapi-data:/srv/app"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: suriyan
      DATABASE_HOST: my_db_compose
      DATABASE_PORT: 5432
      DATABASE_USERNAME: suriyan
      DATABASE_PASSWORD: suriyan
      DATABASE_SSL: false
    depends_on:
      - db
    networks:
      - strapi-net

networks:
  strapi-net:
    driver: bridge